initial

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,10 +2,14 @@
 
 set -euo pipefail
 
-current_script_path=${BASH_SOURCE[0]}
-plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
-# shellcheck source=./lib/utils.bash
-source "${plugin_dir}/lib/utils.bash"
+source "${ASDF_PLUGIN_PATH}/lib/utils.bash"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
+	fail "asdf-$TOOL_NAME supports release installs only"
+fi
+
+# Download tar.gz file to the download directory
+make -C ${ASDF_PLUGIN_PATH}/lib install REF="v$ASDF_INSTALL_VERSION" || (
+	fail "An error occurred while installing $TOOL_NAME $version."
+)
